title: Anton Ustinov
description: My Personal Blog
author: Anton Ustinov
logo: https://osvaldshpengler.github.io/static/img/avatar.png
github: https://github.com/osvaldshpengler
about: Backend developer at FORUMHOUSE
disqus_shortname: osvaldshpengler
google_analytics:
urls:
    - text: Home
      url: /
      icon: fa-home
      layout: post
    - text: About
      url: /about/
      icon: fa-comments
    - text: Resume
      url: '#'
      icon: fa-graduation-cap
    - text: Github
      url: https://github.com/osvaldshpengler
      icon: fa-github

social:
    - icon: fa-facebook
      link: '#'
    - icon: fa-twitter
      link: '#'
    - icon: fa-linkedin
      link: '#'

share:
  twitter_username: \#
  fb_appid: 000000000000

sass:
  sass_dir: _sass
  style: compressed


enableTags: true
tagarray: []

url: "https://osvaldshpengler.github.io/"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist
