title: Anton Ustinov
description: My Personal Blog
author: Anton Ustinov
logo: https://osvaldshpengler.github.io/static/img/avatar.png
github: https://github.com/osvaldshpengler
about: Backend developer at FORUMHOUSE
disqus_shortname: osvaldshpengler
google_analytics:
urls:
    - text: Главная
      url: /
      icon: fa-home
      layout: post
    - text: Web
      url: /web
      icon: fa-code
      layout: post
    - text: Python
      url: /python
      icon: fa-server
      layout: post
    - text: Data Science
      url: /ml
      icon: fa-line-chart
      layout: post
    - text: Обо мне
      url: /about/
      icon: fa-comments
    - text: Github
      url: https://github.com/osvaldshpengler
      icon: fa-github

social:
    - icon: fa-facebook
      link: 'https://www.facebook.com/ustinov.ant'
    - icon: fa-twitter
      link: 'https://twitter.com/UstinovAnt'
    - icon: fa-linkedin
      link: 'https://www.linkedin.com/in/ustinovanton'

share:
  twitter_username: \#
  fb_appid: 000000000000

sass:
  sass_dir: _sass
  style: compressed


enableTags: true
tagarray: []

url: "https://osvaldshpengler.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist
